# Generated by Django 6.0.7 on 2026-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnresolvedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
