# Generated by Django 6.0.7 on 2026-07-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_category_alter_document_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='indexed_chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='indexing_error',
            field=models.TextField(blank=True),
        ),
    ]
